//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PruebaWS.Prueba {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WS_IntegrARSoap", Namespace="http://tempuri.org/")]
    public partial class WS_IntegrAR : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HolaMundoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ImportarVisitaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ComprobarSeguridadOperationCompleted;
        
        private System.Threading.SendOrPostCallback LimpiarBBDDOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateaIdEtniaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateaIdSexoOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateaidnivelestudiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateaidestadocivilOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateaidsituacionlaboralOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateaincapacidadpermanenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateafnacimientoOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateafechadOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateafechatOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateamuerteOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateadiagnosticocategoriaAROperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateadiagnosticocodOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateadiagnosticoclasificacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateadiagnosticodesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FormateatratamientocodOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerIdsTratamientosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WS_IntegrAR() {
            this.Url = global::PruebaWS.Properties.Settings.Default.PruebaWS_Prueba_WS_IntegrAR;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HolaMundoCompletedEventHandler HolaMundoCompleted;
        
        /// <remarks/>
        public event ImportarVisitaCompletedEventHandler ImportarVisitaCompleted;
        
        /// <remarks/>
        public event ComprobarSeguridadCompletedEventHandler ComprobarSeguridadCompleted;
        
        /// <remarks/>
        public event LimpiarBBDDCompletedEventHandler LimpiarBBDDCompleted;
        
        /// <remarks/>
        public event FormateaIdEtniaCompletedEventHandler FormateaIdEtniaCompleted;
        
        /// <remarks/>
        public event FormateaIdSexoCompletedEventHandler FormateaIdSexoCompleted;
        
        /// <remarks/>
        public event FormateaidnivelestudiosCompletedEventHandler FormateaidnivelestudiosCompleted;
        
        /// <remarks/>
        public event FormateaidestadocivilCompletedEventHandler FormateaidestadocivilCompleted;
        
        /// <remarks/>
        public event FormateaidsituacionlaboralCompletedEventHandler FormateaidsituacionlaboralCompleted;
        
        /// <remarks/>
        public event FormateaincapacidadpermanenteCompletedEventHandler FormateaincapacidadpermanenteCompleted;
        
        /// <remarks/>
        public event FormateafnacimientoCompletedEventHandler FormateafnacimientoCompleted;
        
        /// <remarks/>
        public event FormateafechadCompletedEventHandler FormateafechadCompleted;
        
        /// <remarks/>
        public event FormateafechatCompletedEventHandler FormateafechatCompleted;
        
        /// <remarks/>
        public event FormateamuerteCompletedEventHandler FormateamuerteCompleted;
        
        /// <remarks/>
        public event FormateadiagnosticocategoriaARCompletedEventHandler FormateadiagnosticocategoriaARCompleted;
        
        /// <remarks/>
        public event FormateadiagnosticocodCompletedEventHandler FormateadiagnosticocodCompleted;
        
        /// <remarks/>
        public event FormateadiagnosticoclasificacionCompletedEventHandler FormateadiagnosticoclasificacionCompleted;
        
        /// <remarks/>
        public event FormateadiagnosticodesCompletedEventHandler FormateadiagnosticodesCompleted;
        
        /// <remarks/>
        public event FormateatratamientocodCompletedEventHandler FormateatratamientocodCompleted;
        
        /// <remarks/>
        public event ObtenerIdsTratamientosCompletedEventHandler ObtenerIdsTratamientosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HolaMundo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HolaMundo() {
            object[] results = this.Invoke("HolaMundo", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HolaMundoAsync() {
            this.HolaMundoAsync(null);
        }
        
        /// <remarks/>
        public void HolaMundoAsync(object userState) {
            if ((this.HolaMundoOperationCompleted == null)) {
                this.HolaMundoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHolaMundoOperationCompleted);
            }
            this.InvokeAsync("HolaMundo", new object[0], this.HolaMundoOperationCompleted, userState);
        }
        
        private void OnHolaMundoOperationCompleted(object arg) {
            if ((this.HolaMundoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HolaMundoCompleted(this, new HolaMundoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ImportarVisita", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long ImportarVisita(string codSeguridad, System.Xml.XmlNode doc) {
            object[] results = this.Invoke("ImportarVisita", new object[] {
                        codSeguridad,
                        doc});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void ImportarVisitaAsync(string codSeguridad, System.Xml.XmlNode doc) {
            this.ImportarVisitaAsync(codSeguridad, doc, null);
        }
        
        /// <remarks/>
        public void ImportarVisitaAsync(string codSeguridad, System.Xml.XmlNode doc, object userState) {
            if ((this.ImportarVisitaOperationCompleted == null)) {
                this.ImportarVisitaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnImportarVisitaOperationCompleted);
            }
            this.InvokeAsync("ImportarVisita", new object[] {
                        codSeguridad,
                        doc}, this.ImportarVisitaOperationCompleted, userState);
        }
        
        private void OnImportarVisitaOperationCompleted(object arg) {
            if ((this.ImportarVisitaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ImportarVisitaCompleted(this, new ImportarVisitaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ComprobarSeguridad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ComprobarSeguridad(string codSeguridad) {
            object[] results = this.Invoke("ComprobarSeguridad", new object[] {
                        codSeguridad});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ComprobarSeguridadAsync(string codSeguridad) {
            this.ComprobarSeguridadAsync(codSeguridad, null);
        }
        
        /// <remarks/>
        public void ComprobarSeguridadAsync(string codSeguridad, object userState) {
            if ((this.ComprobarSeguridadOperationCompleted == null)) {
                this.ComprobarSeguridadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComprobarSeguridadOperationCompleted);
            }
            this.InvokeAsync("ComprobarSeguridad", new object[] {
                        codSeguridad}, this.ComprobarSeguridadOperationCompleted, userState);
        }
        
        private void OnComprobarSeguridadOperationCompleted(object arg) {
            if ((this.ComprobarSeguridadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComprobarSeguridadCompleted(this, new ComprobarSeguridadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LimpiarBBDD", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool LimpiarBBDD(string codSeguridad, int Hospital) {
            object[] results = this.Invoke("LimpiarBBDD", new object[] {
                        codSeguridad,
                        Hospital});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void LimpiarBBDDAsync(string codSeguridad, int Hospital) {
            this.LimpiarBBDDAsync(codSeguridad, Hospital, null);
        }
        
        /// <remarks/>
        public void LimpiarBBDDAsync(string codSeguridad, int Hospital, object userState) {
            if ((this.LimpiarBBDDOperationCompleted == null)) {
                this.LimpiarBBDDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLimpiarBBDDOperationCompleted);
            }
            this.InvokeAsync("LimpiarBBDD", new object[] {
                        codSeguridad,
                        Hospital}, this.LimpiarBBDDOperationCompleted, userState);
        }
        
        private void OnLimpiarBBDDOperationCompleted(object arg) {
            if ((this.LimpiarBBDDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LimpiarBBDDCompleted(this, new LimpiarBBDDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FormateaIdEtnia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FormateaIdEtnia(string valor, int IdCMedico) {
            object[] results = this.Invoke("FormateaIdEtnia", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateaIdEtniaAsync(string valor, int IdCMedico) {
            this.FormateaIdEtniaAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateaIdEtniaAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateaIdEtniaOperationCompleted == null)) {
                this.FormateaIdEtniaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateaIdEtniaOperationCompleted);
            }
            this.InvokeAsync("FormateaIdEtnia", new object[] {
                        valor,
                        IdCMedico}, this.FormateaIdEtniaOperationCompleted, userState);
        }
        
        private void OnFormateaIdEtniaOperationCompleted(object arg) {
            if ((this.FormateaIdEtniaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateaIdEtniaCompleted(this, new FormateaIdEtniaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FormateaIdSexo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FormateaIdSexo(string valor, int IdCMedico) {
            object[] results = this.Invoke("FormateaIdSexo", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateaIdSexoAsync(string valor, int IdCMedico) {
            this.FormateaIdSexoAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateaIdSexoAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateaIdSexoOperationCompleted == null)) {
                this.FormateaIdSexoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateaIdSexoOperationCompleted);
            }
            this.InvokeAsync("FormateaIdSexo", new object[] {
                        valor,
                        IdCMedico}, this.FormateaIdSexoOperationCompleted, userState);
        }
        
        private void OnFormateaIdSexoOperationCompleted(object arg) {
            if ((this.FormateaIdSexoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateaIdSexoCompleted(this, new FormateaIdSexoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateaidnivelestudios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateaidnivelestudios(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateaidnivelestudios", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateaidnivelestudiosAsync(string valor, int IdCMedico) {
            this.FormateaidnivelestudiosAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateaidnivelestudiosAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateaidnivelestudiosOperationCompleted == null)) {
                this.FormateaidnivelestudiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateaidnivelestudiosOperationCompleted);
            }
            this.InvokeAsync("Formateaidnivelestudios", new object[] {
                        valor,
                        IdCMedico}, this.FormateaidnivelestudiosOperationCompleted, userState);
        }
        
        private void OnFormateaidnivelestudiosOperationCompleted(object arg) {
            if ((this.FormateaidnivelestudiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateaidnivelestudiosCompleted(this, new FormateaidnivelestudiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateaidestadocivil", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateaidestadocivil(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateaidestadocivil", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateaidestadocivilAsync(string valor, int IdCMedico) {
            this.FormateaidestadocivilAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateaidestadocivilAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateaidestadocivilOperationCompleted == null)) {
                this.FormateaidestadocivilOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateaidestadocivilOperationCompleted);
            }
            this.InvokeAsync("Formateaidestadocivil", new object[] {
                        valor,
                        IdCMedico}, this.FormateaidestadocivilOperationCompleted, userState);
        }
        
        private void OnFormateaidestadocivilOperationCompleted(object arg) {
            if ((this.FormateaidestadocivilCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateaidestadocivilCompleted(this, new FormateaidestadocivilCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateaidsituacionlaboral", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateaidsituacionlaboral(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateaidsituacionlaboral", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateaidsituacionlaboralAsync(string valor, int IdCMedico) {
            this.FormateaidsituacionlaboralAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateaidsituacionlaboralAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateaidsituacionlaboralOperationCompleted == null)) {
                this.FormateaidsituacionlaboralOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateaidsituacionlaboralOperationCompleted);
            }
            this.InvokeAsync("Formateaidsituacionlaboral", new object[] {
                        valor,
                        IdCMedico}, this.FormateaidsituacionlaboralOperationCompleted, userState);
        }
        
        private void OnFormateaidsituacionlaboralOperationCompleted(object arg) {
            if ((this.FormateaidsituacionlaboralCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateaidsituacionlaboralCompleted(this, new FormateaidsituacionlaboralCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateaincapacidadpermanente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateaincapacidadpermanente(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateaincapacidadpermanente", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateaincapacidadpermanenteAsync(string valor, int IdCMedico) {
            this.FormateaincapacidadpermanenteAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateaincapacidadpermanenteAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateaincapacidadpermanenteOperationCompleted == null)) {
                this.FormateaincapacidadpermanenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateaincapacidadpermanenteOperationCompleted);
            }
            this.InvokeAsync("Formateaincapacidadpermanente", new object[] {
                        valor,
                        IdCMedico}, this.FormateaincapacidadpermanenteOperationCompleted, userState);
        }
        
        private void OnFormateaincapacidadpermanenteOperationCompleted(object arg) {
            if ((this.FormateaincapacidadpermanenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateaincapacidadpermanenteCompleted(this, new FormateaincapacidadpermanenteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateafnacimiento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateafnacimiento(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateafnacimiento", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateafnacimientoAsync(string valor, int IdCMedico) {
            this.FormateafnacimientoAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateafnacimientoAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateafnacimientoOperationCompleted == null)) {
                this.FormateafnacimientoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateafnacimientoOperationCompleted);
            }
            this.InvokeAsync("Formateafnacimiento", new object[] {
                        valor,
                        IdCMedico}, this.FormateafnacimientoOperationCompleted, userState);
        }
        
        private void OnFormateafnacimientoOperationCompleted(object arg) {
            if ((this.FormateafnacimientoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateafnacimientoCompleted(this, new FormateafnacimientoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateafechad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateafechad(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateafechad", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateafechadAsync(string valor, int IdCMedico) {
            this.FormateafechadAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateafechadAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateafechadOperationCompleted == null)) {
                this.FormateafechadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateafechadOperationCompleted);
            }
            this.InvokeAsync("Formateafechad", new object[] {
                        valor,
                        IdCMedico}, this.FormateafechadOperationCompleted, userState);
        }
        
        private void OnFormateafechadOperationCompleted(object arg) {
            if ((this.FormateafechadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateafechadCompleted(this, new FormateafechadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateafechat", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateafechat(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateafechat", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateafechatAsync(string valor, int IdCMedico) {
            this.FormateafechatAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateafechatAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateafechatOperationCompleted == null)) {
                this.FormateafechatOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateafechatOperationCompleted);
            }
            this.InvokeAsync("Formateafechat", new object[] {
                        valor,
                        IdCMedico}, this.FormateafechatOperationCompleted, userState);
        }
        
        private void OnFormateafechatOperationCompleted(object arg) {
            if ((this.FormateafechatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateafechatCompleted(this, new FormateafechatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateamuerte", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateamuerte(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateamuerte", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateamuerteAsync(string valor, int IdCMedico) {
            this.FormateamuerteAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateamuerteAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateamuerteOperationCompleted == null)) {
                this.FormateamuerteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateamuerteOperationCompleted);
            }
            this.InvokeAsync("Formateamuerte", new object[] {
                        valor,
                        IdCMedico}, this.FormateamuerteOperationCompleted, userState);
        }
        
        private void OnFormateamuerteOperationCompleted(object arg) {
            if ((this.FormateamuerteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateamuerteCompleted(this, new FormateamuerteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FormateadiagnosticocategoriaAR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FormateadiagnosticocategoriaAR(string valor) {
            object[] results = this.Invoke("FormateadiagnosticocategoriaAR", new object[] {
                        valor});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateadiagnosticocategoriaARAsync(string valor) {
            this.FormateadiagnosticocategoriaARAsync(valor, null);
        }
        
        /// <remarks/>
        public void FormateadiagnosticocategoriaARAsync(string valor, object userState) {
            if ((this.FormateadiagnosticocategoriaAROperationCompleted == null)) {
                this.FormateadiagnosticocategoriaAROperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateadiagnosticocategoriaAROperationCompleted);
            }
            this.InvokeAsync("FormateadiagnosticocategoriaAR", new object[] {
                        valor}, this.FormateadiagnosticocategoriaAROperationCompleted, userState);
        }
        
        private void OnFormateadiagnosticocategoriaAROperationCompleted(object arg) {
            if ((this.FormateadiagnosticocategoriaARCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateadiagnosticocategoriaARCompleted(this, new FormateadiagnosticocategoriaARCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateadiagnosticocod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateadiagnosticocod(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateadiagnosticocod", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateadiagnosticocodAsync(string valor, int IdCMedico) {
            this.FormateadiagnosticocodAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateadiagnosticocodAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateadiagnosticocodOperationCompleted == null)) {
                this.FormateadiagnosticocodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateadiagnosticocodOperationCompleted);
            }
            this.InvokeAsync("Formateadiagnosticocod", new object[] {
                        valor,
                        IdCMedico}, this.FormateadiagnosticocodOperationCompleted, userState);
        }
        
        private void OnFormateadiagnosticocodOperationCompleted(object arg) {
            if ((this.FormateadiagnosticocodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateadiagnosticocodCompleted(this, new FormateadiagnosticocodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateadiagnosticoclasificacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateadiagnosticoclasificacion(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateadiagnosticoclasificacion", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateadiagnosticoclasificacionAsync(string valor, int IdCMedico) {
            this.FormateadiagnosticoclasificacionAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateadiagnosticoclasificacionAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateadiagnosticoclasificacionOperationCompleted == null)) {
                this.FormateadiagnosticoclasificacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateadiagnosticoclasificacionOperationCompleted);
            }
            this.InvokeAsync("Formateadiagnosticoclasificacion", new object[] {
                        valor,
                        IdCMedico}, this.FormateadiagnosticoclasificacionOperationCompleted, userState);
        }
        
        private void OnFormateadiagnosticoclasificacionOperationCompleted(object arg) {
            if ((this.FormateadiagnosticoclasificacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateadiagnosticoclasificacionCompleted(this, new FormateadiagnosticoclasificacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateadiagnosticodes", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateadiagnosticodes(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateadiagnosticodes", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateadiagnosticodesAsync(string valor, int IdCMedico) {
            this.FormateadiagnosticodesAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateadiagnosticodesAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateadiagnosticodesOperationCompleted == null)) {
                this.FormateadiagnosticodesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateadiagnosticodesOperationCompleted);
            }
            this.InvokeAsync("Formateadiagnosticodes", new object[] {
                        valor,
                        IdCMedico}, this.FormateadiagnosticodesOperationCompleted, userState);
        }
        
        private void OnFormateadiagnosticodesOperationCompleted(object arg) {
            if ((this.FormateadiagnosticodesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateadiagnosticodesCompleted(this, new FormateadiagnosticodesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Formateatratamientocod", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Formateatratamientocod(string valor, int IdCMedico) {
            object[] results = this.Invoke("Formateatratamientocod", new object[] {
                        valor,
                        IdCMedico});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FormateatratamientocodAsync(string valor, int IdCMedico) {
            this.FormateatratamientocodAsync(valor, IdCMedico, null);
        }
        
        /// <remarks/>
        public void FormateatratamientocodAsync(string valor, int IdCMedico, object userState) {
            if ((this.FormateatratamientocodOperationCompleted == null)) {
                this.FormateatratamientocodOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFormateatratamientocodOperationCompleted);
            }
            this.InvokeAsync("Formateatratamientocod", new object[] {
                        valor,
                        IdCMedico}, this.FormateatratamientocodOperationCompleted, userState);
        }
        
        private void OnFormateatratamientocodOperationCompleted(object arg) {
            if ((this.FormateatratamientocodCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FormateatratamientocodCompleted(this, new FormateatratamientocodCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerIdsTratamientos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] ObtenerIdsTratamientos(string codigo, int idCentro) {
            object[] results = this.Invoke("ObtenerIdsTratamientos", new object[] {
                        codigo,
                        idCentro});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerIdsTratamientosAsync(string codigo, int idCentro) {
            this.ObtenerIdsTratamientosAsync(codigo, idCentro, null);
        }
        
        /// <remarks/>
        public void ObtenerIdsTratamientosAsync(string codigo, int idCentro, object userState) {
            if ((this.ObtenerIdsTratamientosOperationCompleted == null)) {
                this.ObtenerIdsTratamientosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerIdsTratamientosOperationCompleted);
            }
            this.InvokeAsync("ObtenerIdsTratamientos", new object[] {
                        codigo,
                        idCentro}, this.ObtenerIdsTratamientosOperationCompleted, userState);
        }
        
        private void OnObtenerIdsTratamientosOperationCompleted(object arg) {
            if ((this.ObtenerIdsTratamientosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerIdsTratamientosCompleted(this, new ObtenerIdsTratamientosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void HolaMundoCompletedEventHandler(object sender, HolaMundoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HolaMundoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HolaMundoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ImportarVisitaCompletedEventHandler(object sender, ImportarVisitaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ImportarVisitaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ImportarVisitaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ComprobarSeguridadCompletedEventHandler(object sender, ComprobarSeguridadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComprobarSeguridadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComprobarSeguridadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void LimpiarBBDDCompletedEventHandler(object sender, LimpiarBBDDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LimpiarBBDDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LimpiarBBDDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateaIdEtniaCompletedEventHandler(object sender, FormateaIdEtniaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateaIdEtniaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateaIdEtniaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateaIdSexoCompletedEventHandler(object sender, FormateaIdSexoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateaIdSexoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateaIdSexoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateaidnivelestudiosCompletedEventHandler(object sender, FormateaidnivelestudiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateaidnivelestudiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateaidnivelestudiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateaidestadocivilCompletedEventHandler(object sender, FormateaidestadocivilCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateaidestadocivilCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateaidestadocivilCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateaidsituacionlaboralCompletedEventHandler(object sender, FormateaidsituacionlaboralCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateaidsituacionlaboralCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateaidsituacionlaboralCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateaincapacidadpermanenteCompletedEventHandler(object sender, FormateaincapacidadpermanenteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateaincapacidadpermanenteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateaincapacidadpermanenteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateafnacimientoCompletedEventHandler(object sender, FormateafnacimientoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateafnacimientoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateafnacimientoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateafechadCompletedEventHandler(object sender, FormateafechadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateafechadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateafechadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateafechatCompletedEventHandler(object sender, FormateafechatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateafechatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateafechatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateamuerteCompletedEventHandler(object sender, FormateamuerteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateamuerteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateamuerteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateadiagnosticocategoriaARCompletedEventHandler(object sender, FormateadiagnosticocategoriaARCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateadiagnosticocategoriaARCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateadiagnosticocategoriaARCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateadiagnosticocodCompletedEventHandler(object sender, FormateadiagnosticocodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateadiagnosticocodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateadiagnosticocodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateadiagnosticoclasificacionCompletedEventHandler(object sender, FormateadiagnosticoclasificacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateadiagnosticoclasificacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateadiagnosticoclasificacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateadiagnosticodesCompletedEventHandler(object sender, FormateadiagnosticodesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateadiagnosticodesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateadiagnosticodesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FormateatratamientocodCompletedEventHandler(object sender, FormateatratamientocodCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FormateatratamientocodCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FormateatratamientocodCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void ObtenerIdsTratamientosCompletedEventHandler(object sender, ObtenerIdsTratamientosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerIdsTratamientosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerIdsTratamientosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591